### ISSUE TITLE
Error when trying to convert Laur - You are the Miserable (by Yokkako)

### ISSUE THREAD

**Issue by Yokkako** [Ludeo/intralism-tool-collection#8]
map already manually converted to v2 using special dll
[error.txt](https://github.com/Ludeo/intralism-tool-collection/files/5720296/error.txt)

**Comment by Ludeo** [comment]
Moved this issue over to [IntralismManiaConverter](https://github.com/Redageddon/IntralismManiaConverter/issues/5)
